---
- hosts: all
  vars:
    region: us-east-1
    instance_type: db.m1.small # db.m3.medium
    source_cidr: 74.118.27.110/32
  vars_prompt:
    - name: "master_password"
      prompt: "Enter password for the instance's master username"
      private: yes
    - name: "admin_password"
      prompt: "Enter the password for the PhotoSupreme administrator (idimager_main)"
      private: yes

  tasks:
    - name: create a vpc
      ec2_vpc:
        state: present
        cidr_block: 10.0.0.0/16
        region: "{{ region }}"
        resource_tags: { "Name" : "photo-catalog" }
        subnets:
          - cidr: 10.0.0.0/24
            az: "{{ region }}a"
            resource_tags: { "Name" : "photo-catalog" }
          - cidr: 10.0.1.0/24
            az: "{{ region }}b"
            resource_tags: { "Name" : "photo-catalog" }
        internet_gateway: yes
        dns_support: yes
        dns_hostnames: yes
        route_tables:
          - subnets:
              - 10.0.0.0/24
              - 10.0.1.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
      register: vpc

    - name: create the vpc security group
      ec2_group:
        name: photo-catalog-security-group
        description: 'Photo catalog security group'
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 5432
            to_port: 5432
            cidr_ip: "{{ source_cidr }}"
      register: sg

    - name: create the rds subnet group
      rds_subnet_group:
        state: present
        region: "{{ region }}"
        name: photo-catalog-subnet-group
        description: 'Photo catalog subnet group'
        subnets: "{{ vpc.subnets | map(attribute='id') | list}}"

    - name: create the photo catalog instance & database
      rds:
        command: create
        db_engine: postgres
        port: 5432
        size: 100
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        instance_name: photo-catalog
        username: master_user
        password: "{{ master_password }}"
        db_name: photosupreme
        subnet: photo-catalog-subnet-group
        vpc_security_groups: "{{ sg.group_id }}"
        upgrade: yes
        wait: yes
        wait_timeout: 3000 # 50 minutes
      register: rds

    - name: create photo supreme database user
      postgresql_user:
        db=photosupreme
        name=idimager_main
        password="{{ admin_password }}"
        role_attr_flags=CREATEDB,NOSUPERUSER
        priv=ALL
