---
# configurring hosts.ini: https://djaodjin.com/blog/deploying-on-ec2-with-ansible.blog.html

- hosts: all
  vars:
    region: us-east-1
    source_cidrs:
#          - proto: tcp
#            from_port: 5432
#            to_port: 5432
#            cidr_ip: "xxx.xxx.xxx.xxx/yy"
          - proto: tcp
            from_port: 5432
            to_port: 5432
            cidr_ip: "0.0.0.0/0" # wide open

    instance_type: db.m1.small # db.m3.medium
    max_connections: 100
    shared_buffers: 55706 # '{DBInstanceClassMemory/32768}'
    effective_cache_size: 167117 # '{DBInstanceClassMemory*75/819200}'
    work_mem: 17826 # '{DBInstanceClassMemory/102400}' # max_connections * 1024 = 102400

  vars_prompt:
    - name: "master_password"
      prompt: "Enter password for the instance's master username"
      private: yes
    - name: "admin_password"
      prompt: "Enter the password for the PhotoSupreme administrator (idimager_main)"
      private: yes

  tasks:
    - name: create a vpc
      ec2_vpc:
        state: present
        cidr_block: 10.0.0.0/16
        region: "{{ region }}"
        resource_tags: { "Name" : "photo-catalog" }
        subnets:
          - cidr: 10.0.0.0/24
            az: "{{ region }}a"
            resource_tags: { "Name" : "photo-catalog" }
          - cidr: 10.0.1.0/24
            az: "{{ region }}b"
            resource_tags: { "Name" : "photo-catalog" }
        internet_gateway: yes
        dns_support: yes
        dns_hostnames: yes
      register: vpc

    - name: create the vpc security group
      ec2_group:
        name: default
        description: 'Photo catalog security group'
        vpc_id: "{{ vpc.vpc_id }}"
        region: "{{ region }}"
        rules: "{{ source_cidrs }}"
      register: sg

    - name: create the rds subnet group
      rds_subnet_group:
        state: present
        region: "{{ region }}"
        name: photo-catalog-subnet-group
        description: 'Photo catalog subnet group'
        subnets: "{{ vpc.subnets | map(attribute='id') | list}}"

#    - name: create a parameter group
#      rds_param_group:
#        state: present
#        name: photo-catalog-parameter-group
#        description: 'Parameters for Photo Supreme'
#        engine: postgres9.3
#        region: "{{ region }}"
#        params:
#          max_connections: '{{ max_connections }}'
#          shared_buffers: '{{ shared_buffers }}'
#          effective_cache_size: '{{ effective_cache_size }}'
#          work_mem: '{{ work_mem }}'

#    - name: create the photo catalog instance & database
#      rds:
#        command: create
#        db_engine: postgres
#        port: 5432
#        size: 100
#        iops: 1000 # determines ssd vs. magnetic storage
#        region: "{{ region }}"
#        instance_type: "{{ instance_type }}"
#        instance_name: photo-catalog
#        username: master_user
#        password: "{{ master_password }}"
#        subnet: photo-catalog-subnet-group
#        vpc_security_groups: "{{ sg.group_id }}"
#        parameter_group: photo-catalog-parameter-group
#        publicly_accessible: yes
#        upgrade: yes
#        wait: yes
#        wait_timeout: 3000 # 50 minutes
#      register: rds

    - name: create photo supreme database
      postgresql_db:
        name: "photosupreme"
        owner: "master_user"
        encoding: "UTF-8"
        login_host: "photo-catalog.cf3jqjy0lfne.us-east-1.rds.amazonaws.com"
        login_user: "master_user"
        login_password: "{{ master_password }}"

    - name: create photo supreme database user
      postgresql_user:
        db: "photosupreme"
        name: "idimager_main"
        password: "{{ admin_password }}"
        role_attr_flags: "CREATEDB,NOSUPERUSER"
        priv: "ALL"
        login_host: "photo-catalog.cf3jqjy0lfne.us-east-1.rds.amazonaws.com"
        login_user: "master_user"
        login_password: "{{ master_password }}"
